### ISSUE TITLE
The certificate files is out of date

### ISSUE THREAD

**Issue by belang** [vrk-kpa/xroad-public#6] opened 2016-08-15 09:32 UTC
​The xroad-public/configuration-ClientTest.java use certificates in the source file, 

but in the file 'test-conf-detached.txt', the 'Expired-Date' is set to 2016-05-20.

So, an Error: OutdatedGlobalConf: Configuration instance EE expired on 2016-05-21T01:42:55.000+08:00 occures.

I try to change the date in it, but it fails to verify the signature. 

what should I do?

**Comment by iluwatar** [comment] 2016-08-16 13:10
This issue seems to be duplicate of #4 

@belang if you agree please close this issue.

**Closed** 2016-09-05 00:43 UTC
