### ISSUE TITLE
rpm package installation fails, if /tmp is mounted with noexec

### ISSUE THREAD

**Issue by EeroVolotinenCodemen** [vrk-kpa/xroad-public#3] opened 2016-06-07 16:36 UTC
Installation on RHEL 7 fails with rpm, if /tmp is mounted with noexec switch.

**Comment by iluwatar** [comment] 2016-06-08 07:57
We tried this and for us the installation succeeds, but starting the admin UI fails. What version are you installling? At which point the installation stops and what error message do you get?

**Comment by EeroVolotinenCodemen** [comment] 2016-06-08 09:01
Yes, description was a bit unclear. So, I got same issue. How to fix this issue by manually? Please fix this also in packaging?

Eero

**Comment by jhyoty** [comment] 2016-06-08 09:43
Changing the JNA temporary directory should fix the problem. This can be done by manually adding the following line to /etc/xroad/services/local.conf (should initially be empty) and restarting the xroad-jetty service:
`XROAD_PARAMS=" -Djna.tmpdir=/var/lib/xroad $XROAD_PARAMS "`

**Comment by EeroVolotinenCodemen** [comment] 2016-06-08 11:40
Thanks a lot. This fixed the problem. Please add it to official packaging also. Problem occurs on hardened system (like CIS Level 1)

Eero

**Comment by iluwatar** [comment] 2016-06-09 07:28
The issue is fixed and will be included in future releases.

**Closed** 2016-06-09 07:39 UTC
